
// © ATHBuys

//@version=5
strategy("udemy project", overlay=true)

//***********NOTES TO SELF


//why doesn't stoch k crossunder work for values over 100?

//why don't sell alerts show when atr is enabled?

//how to keep oscillator in view and still draw arrows on chart

//TO DO:

//add string based strat selector function- check 3:12 project 3 vid
    //esp. drop down menu part
    
    
//seperate oscillator into functioning part on github


//*************ACTUAL CODE STARTS HERE

//INPUTS

//cci

cciLen = input.int(20, minval=1, title="CCI Length")
src = input.source(hlc3, title="CCI Source")
cciBuyTrigger = input.int(-300, title="CCI buy level")
cciSellTrigger = input.int(300, title="CCI sell level")

//atr

atrLen = input.int(14, title="ATR Length", minval=1)
atrPivot = input.int(70, title="ATR pivot")
atrSmoother = input.int(10, title="ATR smoother")

//use atr or not
useAtr = input.bool(false, title="use atr for alert")

//stochs

smoothK = input.int(3, "K", minval=1)
smoothD = input.int(3, "D", minval=1)
lengthRSI = input.int(14, "RSI Length", minval=1)
lengthStoch = input.int(14, "stchRSI Stochastic Length", minval=1)
stchRSIsrc = input.source(close, title="stchRSI RSI Source")
stochsBuyTrigger = input.int(2, title="stochs buy level")
stochsSellTrigger = input.int(100, title="stochs sell level")


//**********MAFFS PART


//*****************CCI code *******************

cci = ta.cci(src, cciLen)

//CCI strategy

//cciBuyCond = ta.crossover(cci, cciBuyTrigger)
//cciSellCond = ta.crossunder(cci, cciSellTrigger)

//here we have shortened this to a function outputting a tuple
cciOutputs()=>
    buy = ta.crossover(cci, cciBuyTrigger)
    sell = ta.crossunder(cci, cciSellTrigger)
    [buy, sell]
    
[cciBuyCond, cciSellCond] = cciOutputs()

//*****************ATR code *******************

//divided by 10 to make oscillators visible (scaling)
atr = (ta.atr(atrLen)/atrSmoother)

//************ ATR strat

//atrBuyCond = atr < atrPivot
//atrSellCond = atr > atrPivot

//again separate variables above

atrOutputs(atrIn, pivotPoint)=>
    buy = atrIn < pivotPoint
    sell = atrIn > pivotPoint
    [buy, sell]
    
[atrBuyCond, atrSellCond] = atrOutputs(atr, atrPivot)
//i've used these conds to change the color of the background

//*****************stoch rsi code *******************

rsi1 = ta.rsi(stchRSIsrc, lengthRSI)
k = ta.sma(ta.stoch(rsi1, rsi1, rsi1, lengthStoch), smoothK)
d = ta.sma(k, smoothD)

//******* stochs strat

//NB --- need to figure out the mystery of this stochs thing- why the fuck doesn't the sell work if crossunder is set to more than 100?
stochBuyCond = ta.crossover(k, stochsBuyTrigger)
stochSellCond = ta.crossunder(k, stochsSellTrigger)

//Alert conditions

//base buy condition
baseBuyCond = stochBuyCond and cciBuyCond
baseSellCond = stochSellCond and cciSellCond

//buy condition incl atr
atrAlertBuyCond = baseBuyCond and atrBuyCond
atrAlertSellCond = baseSellCond and atrSellCond

//alerts 
buyAlert = useAtr ? atrAlertBuyCond : baseBuyCond
//alertcondition(buyAlert, title="buy alert")

sellAlert = useAtr ? atrAlertSellCond : baseSellCond
//alertcondition(sellAlert, title="sell alert")

//********PLOTS

plotshape(buyAlert  ? 1 : na, title= "buyski", text="buy", style= shape.arrowup, location=location.belowbar, color=color.green, size=size.large)
plotshape(sellAlert ? -1 : na, title="sellski", text="sell", style=shape.arrowdown, location=location.abovebar, color=color.red, size=size.large)


//entry execution

if buyAlert
    strategy.entry("going long", strategy.long)
    
if sellAlert
    strategy.entry("shortski", strategy.short)


